#!/bin/sh
base=$(pwd)
sudo  vmbuilder vbox ubuntu --suite=precise \
    --verbose --debug \
    --arch i386 \
    --flavour generic \
    --dest $base/mediawiki \
    --hostname mediawiki \
    --swapsize 512 \
    --rootsize 8192 \
    --user mediawiki \
    --pass mediawiki \
    --components main,universe,multiverse \
    --addpkg openssh-server \
    --addpkg acpid \
    --addpkg vim \
    --addpkg wget \
    --addpkg curl \
    --addpkg pwgen \
    --addpkg memcached \
    --addpkg apache2-mpm-prefork \
    --addpkg libapache2-mod-php5 \
    --addpkg php5-cli \
    --addpkg php-pear \
    --addpkg php5-curl \
    --addpkg php5-mysql \
    --addpkg php-apc \
    --addpkg php5-gd \
    --addpkg php5-intl \
    --addpkg mysql-server \
    --addpkg imagemagick \
    --addpkg git-core \
    --addpkg avahi-daemon \
    --addpkg ffmpeg \
    --addpkg ffmpeg2theora \
    --execscript=$base/install.sh \
    --firstboot=$base/firstboot.sh
